name: Test R2 Downloader

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
      - 'mlc-r2-downloader.sh'
      - '.github/workflows/test-downloader.yml'
  pull_request_target:
    types: [opened,closed,synchronize]
    branches: [ main ]
    paths:
      - 'mlc-r2-downloader.sh'
      - '.github/workflows/test-downloader.yml'

# Prevent multiple runs from the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    runs-on: ubuntu-latest
    environment: testing
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Load secrets
      id: op-load-secrets
      uses: 1password/load-secrets-action@v2
      with:
        export-env: false
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        CF_ACCESS_CLIENT_ID: "op://x4h33jlflygxmifnxfrizew4oa/7g2fhcv3tpsogr2vhkielewvsm/wsyxxjrdsyj36zsaanbh3kybfe"
        CF_ACCESS_CLIENT_SECRET: "op://x4h33jlflygxmifnxfrizew4oa/7g2fhcv3tpsogr2vhkielewvsm/5x3sr7bry5a3ealsemvx5vcbuy"
      
    - name: Test script with debug mode
      run: |
        # First test with debug mode
        bash ./mlc-r2-downloader.sh -xs https://auth-test.mlcommons-storage.org/metadata/dataset.uri
        
    - name: Test script with service account and testing mode
      env:
        CF_ACCESS_CLIENT_ID: ${{ steps.op-load-secrets.outputs.CF_ACCESS_CLIENT_ID }}
        CF_ACCESS_CLIENT_SECRET: ${{ steps.op-load-secrets.outputs.CF_ACCESS_CLIENT_SECRET }}
      run: |
        # Run script with service account and testing mode flags
        bash ./mlc-r2-downloader.sh -st https://auth-test.mlcommons-storage.org/metadata/dataset.uri 